### PR TITLE
[BUG] Fix reserve slots failed due to take buffer stuck

### LINKED ISSUE #280: [BUG] Reserve slots failed due to take buffer stuck.
### How to reproduce the bug?
Steps to reproduce the bug.

### Could you share logs or screenshots?

> Exception when askSync ReserveSlots for sparkapp-77039902-0001-0.
> 22/07/26 00:23:24.785 ERROR LifecycleManager: [reserveSlots] Failed to reserve buffers for sparkapp-77039902-0001-0 from worker Host:33.143.86.120:RpcPort:9095:PushPort:37075:FetchPort:34273:ReplicatePort:39393. Reason: Exception when askSync ReserveSlots for sparkapp-77039902-0001-0. Exception thrown in awaitResult:

jstack trace:

> "dispatcher-event-loop-3" #14 daemon prio=5 os_prio=0 tid=0x00007f91620d2000 nid=0x26e waiting on condition [0x00007f913c177000]
>    java.lang.Thread.State: TIMED_WAITING (parking)
> 	at sun.misc.Unsafe.park0(Native Method)
> 	- parking to wait for  <0x00000000abb84cf0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
> 	at sun.misc.Unsafe.park(Unsafe.java:1025)
> 	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:216)
> 	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
> 	at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:471)
> 	at com.aliyun.emr.rss.service.deploy.worker.DiskFlusher.takeBuffer(LocalStorageManager.scala:129)
> 	at com.aliyun.emr.rss.service.deploy.worker.FileWriter.takeBuffer(FileWriter.java:320)
> 	at com.aliyun.emr.rss.service.deploy.worker.FileWriter.<init>(FileWriter.java:136)
> 	at com.aliyun.emr.rss.service.deploy.worker.LocalStorageManager.createWriter(LocalStorageManager.scala:393)
> 	at com.aliyun.emr.rss.service.deploy.worker.LocalStorageManager.createWriter(LocalStorageManager.scala:363)
> 	at com.aliyun.emr.rss.service.deploy.worker.Worker.$anonfun$handleReserveSlots$2(Worker.scala:331)
> 	at com.aliyun.emr.rss.service.deploy.worker.Worker$$Lambda$234/1095165280.apply$mcZI$sp(Unknown Source)
> 	at scala.runtime.java8.JFunction1$mcZI$sp.apply(JFunction1$mcZI$sp.java:23)
> 	at scala.collection.immutable.Range.foreach(Range.scala:158)
> 	at com.aliyun.emr.rss.service.deploy.worker.Worker.com$aliyun$emr$rss$service$deploy$worker$Worker$$handleReserveSlots(Worker.scala:328)
> 	at com.aliyun.emr.rss.service.deploy.worker.Worker$$anonfun$receiveAndReply$1.$anonfun$applyOrElse$1(Worker.scala:284)
> 	at com.aliyun.emr.rss.service.deploy.worker.Worker$$anonfun$receiveAndReply$1$$Lambda$232/90001073.apply$mcV$sp(Unknown Source)
> 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
> 	at com.aliyun.emr.rss.common.metrics.source.AbstractSource.sample(AbstractSource.scala:119)
> 	at com.aliyun.emr.rss.service.deploy.worker.Worker$$anonfun$receiveAndReply$1.applyOrElse(Worker.scala:279)
> 	at com.aliyun.emr.rss.common.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:110)
> 	at com.aliyun.emr.rss.common.rpc.netty.Inbox$$Lambda$93/441305352.apply$mcV$sp(Unknown Source)
> 	at com.aliyun.emr.rss.common.rpc.netty.Inbox.safelyCall(Inbox.scala:214)
> 	at com.aliyun.emr.rss.common.rpc.netty.Inbox.process(Inbox.scala:107)
> 	at com.aliyun.emr.rss.common.rpc.netty.Dispatcher$MessageLoop.run(Dispatcher.scala:222)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:627)
> 	at java.lang.Thread.

run(Thread.java:882)

/cc @who-need-to-know

/assign @who-can-solve-this-bug

### PR DESCRIPTION
**Pull request by FMX**
# [BUG] Fix reserve slots failed due to take buffer stuck

### Related issues.
closes #280 

### How was this patch tested?

/cc @related-reviewer

/assign @main-reviewer

### CODE REVIEW

File: server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/LocalStorageManager.scala [hunk 1]
```diff
@@ -68,12 +68,10 @@ private[worker] final class DiskFlusher(
...
 
   private def init(): Unit = {
-    val actualQueueSize = queueCapacity / threadCount + 1
     for (index <- 0 until (threadCount)) {
-      workingQueues(index) = new LinkedBlockingQueue[FlushTask](actualQueueSize)
-      bufferQueues(index) = new LinkedBlockingQueue[CompositeByteBuf](actualQueueSize)
-      for (_ <- 0 until actualQueueSize) {
-        bufferQueues(index).put(Unpooled.compositeBuffer(256))
+      workingQueues(index) = new LinkedBlockingQueue[FlushTask](queueCapacity)
+      for (_ <- 0 until queueCapacity) {
```
Comment (waitinfuture) [inline server-worker/src/main/scala/com/aliyun/emr/rss/service/deploy/worker/LocalStorageManager.scala:73]: Move this out of the outer loop

**Review by waitinfuture — APPROVED** [review]
LGTM, thanks!

**Review by AngersZhuuuu — COMMENTED** [review]
LGTM
