### PR TITLE
[ISSUE-350] Rewrite RssShuffleManager using Java to pass compile on Spark 3.1+

### LINKED ISSUE #350: [BUG] Failed to compile w/ Spark 3.1
### What is the bug?

The project claims to support Spark 3.x, but I can not compile w/ Spark 3.1.3

```
[INFO] -----------------< com.aliyun.emr:rss-shuffle-manager >-----------------
[INFO] Building Aliyun E-MapReduce Shuffle Service Shuffle Manager for Spark 0.2.0-SNAPSHOT [5/8]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ rss-shuffle-manager ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/chengpan/Projects/remote-shuffle-service/client-spark/shuffle-manager-3/src/main/resources
[INFO]
[INFO] --- scala-maven-plugin:3.3.2:compile (scala-compile-first) @ rss-shuffle-manager ---
[WARNING]  Expected all dependencies to require Scala version: 2.12.10
[WARNING]  org.scala-lang:scala-reflect:2.12.10 requires scala version: 2.12.10
[WARNING]  com.twitter:chill_2.12:0.9.5 requires scala version: 2.12.10
[WARNING]  org.apache.spark:spark-network-common_2.12:3.1.3 requires scala version: 2.12.10
[WARNING]  org.scala-lang.modules:scala-xml_2.12:1.2.0 requires scala version: 2.12.8
[WARNING] Multiple versions of scala libraries detected!
[INFO] /Users/chengpan/Projects/remote-shuffle-service/client-spark/shuffle-manager-3/src/main/java:-1: info: compiling
[INFO] /Users/chengpan/Projects/remote-shuffle-service/client-spark/shuffle-manager-3/src/main/scala:-1: info: compiling
[INFO] Compiling 6 source files to /Users/chengpan/Projects/remote-shuffle-service/client-spark/shuffle-manager-3/target/classes at 1660438235855
[ERROR] /Users/chengpan/Projects/remote-shuffle-service/client-spark/shuffle-manager-3/src/main/scala/org/apache/spark/shuffle/rss/RssShuffleManager.scala:180: error: overriding method getReader in trait ShuffleManager of type [K, C](handle: org.apache.spark.shuffle.ShuffleHandle, startPartition: Int, endPartition: Int, context: org.apache.spark.TaskContext, metrics: org.apache.spark.shuffle.ShuffleReadMetricsReporter)org.apache.spark.shuffle.ShuffleReader[K,C];
[ERROR]  method getReader cannot override final member
[ERROR]   def getReader[K, C](
[ERROR]       ^
[ERROR] one error found
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Aliyun E-MapReduce Shuffle Service Project Parent POM 0.2.0-SNAPSHOT:
[INFO]
[INFO] Aliyun E-MapReduce Shuffle Service Project Parent POM SUCCESS [  0.183 s]
[INFO] Aliyun E-MapReduce Shuffle Service Common .......... SUCCESS [ 12.680 s]
[INFO] Aliyun E-MapReduce Shuffle Service Java Client ..... SUCCESS [  5.030 s]
[INFO] Aliyun E-MapReduce Shuffle Service Shuffle Manager for Spark SUCCESS [  3.181 s]
[INFO] Aliyun E-MapReduce Shuffle Service Shuffle Manager for Spark FAILURE [  1.896 s]
[INFO] Aliyun E-MapReduce Shuffle Service Server Common ... SKIPPED
[INFO] Aliyun E-MapReduce Shuffle Service Service Master Module SKIPPED
[INFO] Aliyun E-MapReduce Shuffle Service Service Worker Module SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

### How to reproduce the bug?
Steps to reproduce the bug.

```
mvn package -DskipTests -Pspark-3 -Plog4j-1 -Dspark.version=3.1.3
```

### Could you share logs or screenshots?
If applicable, add logs/screenshots to help explain your problem.

/cc @who-need-to-know

/assign @who-can-solve-this-bug

### PR DESCRIPTION
**Pull request by pan3793**
# [BUG]/[FEATURE] title

### What changes were proposed in this pull request?

Rewrite RssShuffleManager using Java to pass compile on Spark 3.1+

### Why are the changes needed?

Fix #350

### How was this patch tested?

/cc @related-reviewer

/assign @main-reviewer

### CODE REVIEW

File: client-spark/shuffle-manager-3/src/main/scala/org/apache/spark/shuffle/rss/RssSparkUtils.scala [hunk 1]
```diff
@@ -0,0 +1,91 @@
+/*
```
Comment (waitinfuture) [inline client-spark/shuffle-manager-3/src/main/scala/org/apache/spark/shuffle/rss/RssSparkUtils.scala:1]: Shall we merge this file with SparkUtils.java? I think the only difference between them is java and scala.

Comment (pan3793) [reply client-spark/shuffle-manager-3/src/main/scala/org/apache/spark/shuffle/rss/RssSparkUtils.scala:1]: Do you want to include those reflection utils into this project? it has been adopted by Apache Parquet, Iceberg and Kyuubi.
https://github.com/apache/incubator-kyuubi/tree/master/kyuubi-common/src/main/java/org/apache/kyuubi/reflection

**Review by waitinfuture — APPROVED** [review]
LGTM, thanks!
